const products = [
  {
    _id: '1',
    name: 'Bacon & Broccoli',
    image: '/images/Bacon & Broccoli.png',
    description:
      'Bacon, Onion, Garlic, Broccoli, Olive Oil, Mozarrala Cheese',
    Group: 'Pork',
    category: 'Pizza',
    price: 10,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'BBQ Poncho',
    image: '/images/BBQ Poncho.png',
    description:
      'BBQ sauce, Chicken Breast Fillet, Paprika, Red Onion, Corn ',
    Group: 'Chicken',
    category: 'Pizza',
    price: 12,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Chicken & Red Onion',
    image: '/images/Chicken & Red Onion.png',
    description:
      'Chicken Breast, Red Onion, Mozzarella Cheese',
    Group: 'Chicken',
    category: 'Pizza',
    price: 11,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Chilli Salami & Herder Cheese',
    image: '/images/Chilli Salami & Herder Cheese.png',
    description:
      'Chilli, Salami, Herder Cheese',
    Group: 'Pork',
    category: 'Pizza',
    price: 10,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Conchita',
    image: '/images/Conchita.png',
    description:
      'Groud Beef, BBQ Sauce, Red Onion, Mozzarella Cheese',
    Group: 'Beef',
    category: 'Pizza',
    price: 12,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Creamy Chicken',
    image: '/images/Creamy Chicken.png',
    description:
      'Cream Sauce, Fresh Mushrooms, Chicken Breast fillet, Red Onion, Bacon',
    Group: 'Chicken',
    category: 'Pizza',
    price: 10,
    countInStock: 2,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Gourmet',
    image: '/images/Gourmet.png',
    description:
      'Beef Steak Strips, Green Asparagus, Fresh Tomotoes, Hollandaise Sauce',
    Group: 'Beef',
    category: 'Pizza',
    price: 10,
    countInStock: 2,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Ground Beef & Corn',
    image: '/images/Ground Beef & Corn.png',
    description:
      'Groud Beef, Corn, Spicy Sauce',
    Group: 'Beef',
    category: 'Pizza',
    price: 10,
    countInStock: 2,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '9',
    name: 'Ground Beef & Corn',
    image: '/images/Ground Beef & Corn.png',
    description:
      'Fresh Mushrooms, Red Onion, Mozzarella Cheese',
    Group: 'Veggie',
    category: 'Pizza',
    price: 10,
    countInStock: 2,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '10',
    name: 'Smokey Chicken',
    image: '/images/Smokey Chicken.png',
    description:
      'BBQ Sauce, Chicken Breast Fillet, Red Onion, Cherry Tomatoes, Mozzarella Cheese',
    Group: 'Chicken',
    category: 'Pizza',
    price: 10,
    countInStock: 2,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '11',
    name: 'Steak & Bacon',
    image: '/images/Steak & Bacon.png',
    description:
      'BBQ Sauce, Chicken Breast Fillet, Red Onion, Cherry Tomatoes, Mozzarella Cheese',
    Group: 'Beef',
    category: 'Pizza',
    price: 10,
    countInStock: 2,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '12',
    name: 'Supreme Chicken',
    image: '/images/Supreme Chicken.png',
    description:
      'Fresh Tomatoes, Chicken Breast Fillet, Red Oion, Bell Pepper',
    Group: 'Chicken',
    category: 'Pizza',
    price: 10,
    countInStock: 2,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '13',
    name: 'Teriyaki Chicken',
    image: '/images/Teriyaki Chicken.png',
    description:
      'Chicken Breast Fillet, Broccoli, Spring Onion, Sesame, Teriyaki Sauce',
    Group: 'Chicken',
    category: 'Pizza',
    price: 10,
    countInStock: 2,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '13',
    name: 'Teriyaki Chicken',
    image: '/images/Teriyaki Chicken.png',
    description:
      'Chicken Breast Fillet, Broccoli, Spring Onion, Sesame, Teriyaki Sauce',
    Group: 'Chicken',
    category: 'Pizza',
    price: 10,
    countInStock: 2,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '14',
    name: 'Veggie Chicken',
    image: '/images/Veggie Chicken.png',
    description:
      'Spinach, Vegan Chicken Fillet, Bell Pepper, Feta Cheese',
    Group: 'Veggie',
    category: 'Pizza',
    price: 10,
    countInStock: 2,
    rating: 4,
    numReviews: 12,
  }
]

export default products
